name: app_xtintas
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  awesome_icons: ^1.1.0
  scaffold_gradient_background: ^1.0.3+1
  google_fonts: ^3.0.1
  animations: ^2.0.4
  http: ^0.13.5
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  json_serializable: ^6.3.1


dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
   - assets/

  
